language: node_js
node_js:
  - "6"
  - "5"
  - "4"

services: mongodb

before_install:
 - npm install pm2 -g

before_script:
 - mongo --eval "db.getSiblingDB('stackrank').addUser('dev_user', '12345'); db.getSiblingDB('stackrank').createCollection('users');"
 - pm2 start main.js --name "web-server"

script:
 - npm test

after_script:
 - pm2 stop web-server
 - pm2 delete web-server
