language: node_js
node_js:
  - "5.9"
  - "5.7"
  - "5.6"
  - "4.4"
  - "4.3"
  - "4.2"

before_install:
 - npm install pm2 -g

before_script:
 - pm2 start main.js --name "web-server"

script:
 - npm test

after_script:
 - pm2 stop web-server
 - pm2 delete web-server
